server:
  port: 7590

spring:
  application:
    name: gateway-api
  datasource:
    url: jdbc:postgresql://localhost:5432/TravelMarketPlace
    username: postgres
    password: 123456
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - ApplicationAuthenticationFilter

        - id: TEST-SERVICE
          uri: lb://test-service
          predicates:
            - Path=/pingorder/**
          filters:
            - ApplicationAuthenticationFilter

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/




