server:
  port: 7590

spring:
  application:
    name: gateway-api
  datasource:
    url: jdbc:postgresql://35.240.226.176:5432/travelmarketplace
    username: postgres
    password: capstonevlu
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: '*'
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - ApplicationAuthenticationFilter

        - id: MANAGE-HOTELS
          uri: lb://manage-hotels
          predicates:
            - Path=/partner/api/**
          filters:
            - ApplicationAuthenticationFilter


eureka:
  instance:
#    preferIpAddress: true
    hostname: 34.87.40.248
  client:
    service-url:
      defaultZone: http://34.87.40.248:8761/eureka/




