server:
  port: 7590
  ssl:
    key-store: classpath:partner-https.p12
    key-store-password: capstonevlu
    key-store-type: PKCS12
    key-alias: partner-https
    key-password: capstonevlu
    enabled: true

spring:
  application:
    name: gateway-api
  datasource:
    url: jdbc:postgresql://35.240.226.176:5432/travelmarketplace
    username: postgres
    password: capstonevlu
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders:
              - "Origin"
              - "Content-Type"
              - "Accept"
              - "Authorization"
              - "Referer"
            allowedMethods:
              - POST
              - GET
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/partner/auth/**
          filters:
            - ApplicationAuthenticationFilter

        - id: MANAGE-HOTELS
          uri: lb://manage-hotels
          predicates:
            - Path=/partner/api/**
          filters:
            - ApplicationAuthenticationFilter

        - id: MANAGE-ROOMS
          uri: lb://manage-rooms
          predicates:
            - Path=/partner/**
          filters:
            - ApplicationAuthenticationFilter


eureka:
  instance:
#    preferIpAddress: true
    hostname: 34.87.40.248
  client:
    service-url:
      defaultZone: http://34.87.40.248:8761/eureka/




