server:
  port: 7590

spring:
  application:
    name: gateway-api
  datasource:
    url: jdbc:postgresql://35.240.226.176:5432/travelmarketplace
    username: postgres
    password: capstonevlu
    jpa:
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: AUTH-SERVICE
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - ApplicationAuthenticationFilter


eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://34.143.171.128:8761/eureka/




